"""Add Outbox table.

Revision ID: 5e97aa88e6d3
Revises: 54443c5159d3
Create Date: 2026-03-30 19:08:05.764653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e97aa88e6d3'
down_revision: Union[str, Sequence[str], None] = '54443c5159d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_payment_id'), 'outbox_events', ['payment_id'], unique=False)
    op.create_index('ix_outbox_events_status_next_retry', 'outbox_events', ['status', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_status_next_retry', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_payment_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
